In [18]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## 使用SciKit-Learn套件做決策樹分析

In [2]:
df = pd.read_csv("airline.csv")

In [3]:
df.head()

,user_id,is_loyal,depart_on_time,arrive_on_time,register_method,register_rate,class,seat_rate,meal_rate,flight_rate,...,tv_ad,youtube_ad_1,youtube_ad_2,youtube_ad_3,dm_message,dm_post,dm_email,credit_card_vendor,credit_card_bonus,coupon
0,00411460f7c92d2124a67ea0f4cb5f85,Satisfied,1,1,phone,3,3,3,3,3,...,1,0,1,0,0,0,0,Vendor A,2,196.7
1,006f52e9102a8d3be2fe5614f42ba989,Satisfied,0,0,mobile_app,2,2,4,4,2,...,1,0,0,0,1,1,0,Vendor A,3,53.6
2,00ac8ed3b4327bdd4ebbebcb2ba10a00,Unsatisfied,1,1,others,4,3,1,3,2,...,0,1,1,1,1,0,1,Vendor C,1,107.8
3,00ec53c4682d36f5c4359f4ae7bd7ba1,Unsatisfied,0,0,others,3,3,1,2,2,...,1,1,1,1,1,0,1,Vendor B,2,37.5
4,01161aaa0b6d1345dd8fe4e481144d84,Satisfied,1,1,phone,4,2,4,4,5,...,1,0,0,1,1,0,0,Vendor B,1,43.3

In [4]:
df.drop("user_id", axis=1, inplace=True)

In [5]:
#轉換有階層的類別型資料為數字
size_mapping = {
           'Vendor A': 1,
           'Vendor B': 2,
           'Vendor C': 3}
df['credit_card_vendor'] = df['credit_card_vendor'].map(size_mapping)

In [6]:
#轉換無階層的類別型資料為dummy
from sklearn.preprocessing import OneHotEncoder
pf = pd.get_dummies(df[['register_method']])
df = pd.concat([df, pf], axis=1)
df.drop(['register_method'], axis=1, inplace=True)

In [7]:
df

,is_loyal,depart_on_time,arrive_on_time,register_rate,class,seat_rate,meal_rate,flight_rate,package_rate,tv_ad,...,dm_message,dm_post,dm_email,credit_card_vendor,credit_card_bonus,coupon,register_method_mobile_app,register_method_others,register_method_phone,register_method_website
0,Satisfied,1,1,3,3,3,3,3,3,1,...,0,0,0,1,2,196.7,0,0,1,0
1,Satisfied,0,0,2,2,4,4,2,4,1,...,1,1,0,1,3,53.6,1,0,0,0
2,Unsatisfied,1,1,4,3,1,3,2,2,0,...,1,0,1,3,1,107.8,0,1,0,0
3,Unsatisfied,0,0,3,3,1,2,2,3,1,...,1,0,1,2,2,37.5,0,1,0,0
4,Satisfied,1,1,4,2,4,4,5,3,1,...,1,0,0,2,1,43.3,0,0,1,0
5,Satisfied,1,1,4,3,2,3,4,2,1,...,0,0,1,2,1,160.1,0,0,1,0
6,Satisfied,0,0,2,3,3,2,3,2,1,...,0,0,0,1,3,146.0,0,1,0,0
7,Satisfied,1,1,2,2,4,3,4,3,1,...,0,1,1,2,2,41.4,1,0,0,0
8,Satisfied,1,1,3,3,3,3,4,2,0,...,0,0,0,2,3,124.5,0,1,0,0
9,Unsatisfied,1,1,3,3,2,1,3,2,0,...,1,0,1,2,2,94.8,0,1,0,0
10,Unsatisfied,0,0,5,3,2,3,2,2,0,...,0,0,0,1,2,158.2,0,1,0,0
11,Satisfied,1,1,4,3,2,2,3,4,0,...,0,0,0,3,1,202.3,0,1,0,0
12,Satisfied,1,1,2,2,4,3,5,4,0,...,1,1,1,3,1,58.7,0,0,0,1
13,Satisfied,0,1,4,2,3,4,3,4,1,...,1,0,0,3,3,46.6,0,0,1,0
14,Satisfied,1,1,4,3,3,2,3,3,1,...,0,0,0,2,3,145.0,0,1,0,0
15,Unsatisfied,0,0,2,1,2,3,3,1,1,...,1,1,1,2,2,5.3,0,0,0,1
16,Satisfied,0,0,2,2,4,4,3,4,0,...,0,0,0,1,3,39.4,1,0,0,0
17,Satisfied,1,1,3,3,3,2,3,3,0,...,0,0,0,2,2,173.1,0,1,0,0
18,Satisfied,0,0,2,1,4,4,2,3,1,...,1,0,1,2,1,9.7,0,0,0,1
19,Unsatisfied,0,0,3,2,3,3,3,4,0,...,1,0,1,2,2,42.7,0,0,1,0
20,Unsatisfied,0,0,4,3,2,3,3,3,0,...,0,0,0,2,1,194.6,0,0,1,0
21,Satisfied,1,1,2,3,2,2,4,3,1,...,0,0,0,3,3,111.0,0,1,0,0
22,Unsatisfied,1,1,3,2,4,4,4,4,0,...,1,1,1,2,1,66.8,1,0,0,0
23,Satisfied,1,1,2,3,3,2,4,2,1,...,0,0,0,1,3,70.6,0,1,0,0
24,Satisfied,1,1,4,3,3,3,3,3,0,...,0,0,0,3,3,140.1,0,0,1,0
25,Satisfied,1,1,2,3,1,2,4,3,0,...,0,0,0,3,3,80.8,0,1,0,0
26,Unsatisfied,1,0,1,3,3,3,5,2,0,...,0,0,0,3,2,80.8,0,1,0,0
27,Satisfied,1,1,2,3,3,2,2,2,0,...,0,0,0,2,1,134.2,0,1,0,0
28,Satisfied,1,1,1,3,3,2,1,3,0,...,0,0,0,3,3,138.9,0,1,0,0
29,Unsatisfied,0,0,1,2,3,3,1,3,0,...,1,0,1,2,1,40.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,Unsatisfied,1,1,2,3,2,2,3,2,0,...,0,0,0,2,1,78.3,0,1,0,0
971,Unsatisfied,0,0,4,2,4,3,4,4,0,...,1,0,1,2,1,50.9,0,0,1,0
972,Satisfied,1,1,5,3,2,3,3,4,1,...,0,1,1,2,1,154.7,0,1,0,0
973,Satisfied,1,1,4,3,3,3,4,2,0,...,0,0,0,3,3,152.8,0,0,1,0
974,Satisfied,1,1,2,3,2,3,1,2,0,...,0,0,0,3,3,144.7,0,1,0,0
975,Satisfied,1,1,4,3,2,3,2,2,1,...,0,0,0,1,4,117.7,0,1,0,0
976,Unsatisfied,1,1,2,2,2,2,4,2,0,...,1,1,1,2,1,27.9,1,0,0,0
977,Satisfied,1,1,3,3,3,3,5,3,1,...,0,0,0,3,3,206.6,0,1,0,0
978,Unsatisfied,0,0,5,3,3,3,2,3,0,...,0,0,0,3,1,201.5,0,1,0,0
979,Satisfied,1,1,3,3,3,3,2,3,1,...,0,1,1,2,1,214.7,0,1,0,0
980,Satisfied,1,1,4,3,3,2,3,2,1,...,0,0,0,1,2,101.4,0,0,1,0
981,Unsatisfied,1,1,4,3,2,2,4,3,0,...,1,0,0,2,1,196.1,0,1,0,0
982,Satisfied,1,1,4,2,2,4,1,3,0,...,0,0,0,2,1,41.0,0,0,0,1
983,Satisfied,1,1,2,2,4,3,1,4,0,...,0,0,0,1,4,41.5,1,0,0,0
984,Unsatisfied,1,1,4,3,2,2,2,2,0,...,0,0,0,2,1,52.4,0,1,0,0
985,Satisfied,1,1,4,1,4,3,3,5,0,...,1,1,1,2,3,17.0,0,0,0,1
986,Satisfied,1,1,3,3,4,3,3,2,0,...,0,0,0,2,2,243.2,0,1,0,0
987,Satisfied,1,1,4,3,3,3,4,3,1,...,0,0,1,2,1,121.7,0,1,0,0
988,Unsatisfied,1,1,4,3,2,3,3,2,0,...,1,0,1,1,2,134.2,0,1,0,0
989,Unsatisfied,0,0,5,3,3,3,2,3,0,...,1,0,0,2,2,141.0,0,1,0,0
990,Unsatisfied,1,1,4,3,3,2,1,3,0,...,0,0,0,3,1,99.7,0,1,0,0
991,Unsatisfied,1,1,3,2,4,3,3,3,0,...,1,0,1,2,1,67.1,0,0,1,0
992,Satisfied,0,0,4,2,4,3,3,3,0,...,0,0,0,2,1,38.4,0,0,1,0
993,Unsatisfied,0,0,1,3,1,2,2,1,0,...,0,0,0,2,1,17.5,0,1,0,0
994,Satisfied,1,1,5,3,2,3,3,3,0,...,0,0,0,1,3,105.1,0,1,0,0
995,Unsatisfied,1,1,3,2,4,3,4,3,0,...,1,1,0,2,1,63.5,0,0,0,1
996,Satisfied,1,1,3,3,2,3,3,3,0,...,0,0,1,1,3,194.5,0,1,0,0
997,Satisfied,0,0,4,3,3,2,5,3,1,...,0,0,0,3,1,146.1,0,1,0,0
998,Unsatisfied,0,0,1,3,2,2,4,2,0,...,1,0,1,2,1,221.0,0,1,0,0
999,Unsatisfied,1,1,1,3,3,3,1,3,0,...,0,0,0,2,1,69.3,0,1,0,0

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
#建立測試集跟訓練集
X = df.drop("is_loyal", axis = 1) #除去結果本身的所有變數
Y = df["is_loyal"]
x_train, x_test, y_train, y_test = train_test_split(X, Y,
                                                    test_size=0.20,
                                                    random_state=0)

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
#開函數學習機
dtree = DecisionTreeClassifier()

In [12]:
#訓練
dtree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [13]:
#預測
predictions = dtree.predict(x_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
#評估決策樹結果
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

   Satisfied       0.85      0.88      0.87       125
 Unsatisfied       0.79      0.75      0.77        75

    accuracy                           0.83       200
   macro avg       0.82      0.81      0.82       200
weighted avg       0.83      0.83      0.83       200

In [16]:
#製成混淆矩陣：
print(confusion_matrix(y_test,predictions))
print((94+34)/(94+31+41+34))

[[110  15]
 [ 19  56]]
0.64